# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import rv_pb2 as rv__pb2


class RVStub(object):
    """RV Service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FileUpload = channel.unary_unary(
                '/rv.proto.RV/FileUpload',
                request_serializer=rv__pb2.FileRequest.SerializeToString,
                response_deserializer=rv__pb2.FileResponse.FromString,
                )


class RVServicer(object):
    """RV Service definition.
    """

    def FileUpload(self, request, context):
        """FileUpload accepts a single file upload request and
        returns a status message to the caller.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RVServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FileUpload': grpc.unary_unary_rpc_method_handler(
                    servicer.FileUpload,
                    request_deserializer=rv__pb2.FileRequest.FromString,
                    response_serializer=rv__pb2.FileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rv.proto.RV', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RV(object):
    """RV Service definition.
    """

    @staticmethod
    def FileUpload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rv.proto.RV/FileUpload',
            rv__pb2.FileRequest.SerializeToString,
            rv__pb2.FileResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
