# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rv.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='rv.proto',
  package='rv.proto',
  syntax='proto3',
  serialized_options=b'Z\036github.com/morrowc/rv/proto/rv',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08rv.proto\x12\x08rv.proto\"\xc7\x01\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0b\n\x03md5\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\x0c\x12\x13\n\x0b\x63onvert_sql\x18\x04 \x01(\x08\x12.\n\x07project\x18\x05 \x01(\x0e\x32\x1d.rv.proto.FileRequest.Project\"C\n\x07Project\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0e\n\nROUTEVIEWS\x10\x01\x12\x0c\n\x08RIPE_RIS\x10\x02\x12\r\n\tRPKI_RARC\x10\x03\"\x82\x01\n\x0c\x46ileResponse\x12-\n\x06status\x18\x01 \x01(\x0e\x32\x1d.rv.proto.FileResponse.Status\x12\x15\n\rerror_message\x18\x02 \x01(\t\",\n\x06Status\x12\x0b\n\x07UNKNOWN\x10\x00\x12\x0b\n\x07SUCCESS\x10\x01\x12\x08\n\x04\x46\x41IL\x10\x02\x32\x41\n\x02RV\x12;\n\nFileUpload\x12\x15.rv.proto.FileRequest\x1a\x16.rv.proto.FileResponseB Z\x1egithub.com/morrowc/rv/proto/rvb\x06proto3'
)



_FILEREQUEST_PROJECT = _descriptor.EnumDescriptor(
  name='Project',
  full_name='rv.proto.FileRequest.Project',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ROUTEVIEWS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RIPE_RIS', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RPKI_RARC', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=155,
  serialized_end=222,
)
_sym_db.RegisterEnumDescriptor(_FILEREQUEST_PROJECT)

_FILERESPONSE_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='rv.proto.FileResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='FAIL', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=311,
  serialized_end=355,
)
_sym_db.RegisterEnumDescriptor(_FILERESPONSE_STATUS)


_FILEREQUEST = _descriptor.Descriptor(
  name='FileRequest',
  full_name='rv.proto.FileRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='rv.proto.FileRequest.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='md5', full_name='rv.proto.FileRequest.md5', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='content', full_name='rv.proto.FileRequest.content', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='convert_sql', full_name='rv.proto.FileRequest.convert_sql', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='project', full_name='rv.proto.FileRequest.project', index=4,
      number=5, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FILEREQUEST_PROJECT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=222,
)


_FILERESPONSE = _descriptor.Descriptor(
  name='FileResponse',
  full_name='rv.proto.FileResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='rv.proto.FileResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error_message', full_name='rv.proto.FileResponse.error_message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _FILERESPONSE_STATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=355,
)

_FILEREQUEST.fields_by_name['project'].enum_type = _FILEREQUEST_PROJECT
_FILEREQUEST_PROJECT.containing_type = _FILEREQUEST
_FILERESPONSE.fields_by_name['status'].enum_type = _FILERESPONSE_STATUS
_FILERESPONSE_STATUS.containing_type = _FILERESPONSE
DESCRIPTOR.message_types_by_name['FileRequest'] = _FILEREQUEST
DESCRIPTOR.message_types_by_name['FileResponse'] = _FILERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileRequest = _reflection.GeneratedProtocolMessageType('FileRequest', (_message.Message,), {
  'DESCRIPTOR' : _FILEREQUEST,
  '__module__' : 'rv_pb2'
  # @@protoc_insertion_point(class_scope:rv.proto.FileRequest)
  })
_sym_db.RegisterMessage(FileRequest)

FileResponse = _reflection.GeneratedProtocolMessageType('FileResponse', (_message.Message,), {
  'DESCRIPTOR' : _FILERESPONSE,
  '__module__' : 'rv_pb2'
  # @@protoc_insertion_point(class_scope:rv.proto.FileResponse)
  })
_sym_db.RegisterMessage(FileResponse)


DESCRIPTOR._options = None

_RV = _descriptor.ServiceDescriptor(
  name='RV',
  full_name='rv.proto.RV',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=357,
  serialized_end=422,
  methods=[
  _descriptor.MethodDescriptor(
    name='FileUpload',
    full_name='rv.proto.RV.FileUpload',
    index=0,
    containing_service=None,
    input_type=_FILEREQUEST,
    output_type=_FILERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RV)

DESCRIPTOR.services_by_name['RV'] = _RV

# @@protoc_insertion_point(module_scope)
