//
// Proto Definition for RV data collection/archive.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: rv.proto

package rv

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Project is the sender to the system.
type FileRequest_Project int32

const (
	FileRequest_UNKNOWN        FileRequest_Project = 0
	FileRequest_ROUTEVIEWS     FileRequest_Project = 1
	FileRequest_ROUTEVIEWS_RIB FileRequest_Project = 4
	FileRequest_RIPE_RIS       FileRequest_Project = 2
	FileRequest_RPKI_RARC      FileRequest_Project = 3
)

// Enum value maps for FileRequest_Project.
var (
	FileRequest_Project_name = map[int32]string{
		0: "UNKNOWN",
		1: "ROUTEVIEWS",
		4: "ROUTEVIEWS_RIB",
		2: "RIPE_RIS",
		3: "RPKI_RARC",
	}
	FileRequest_Project_value = map[string]int32{
		"UNKNOWN":        0,
		"ROUTEVIEWS":     1,
		"ROUTEVIEWS_RIB": 4,
		"RIPE_RIS":       2,
		"RPKI_RARC":      3,
	}
)

func (x FileRequest_Project) Enum() *FileRequest_Project {
	p := new(FileRequest_Project)
	*p = x
	return p
}

func (x FileRequest_Project) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileRequest_Project) Descriptor() protoreflect.EnumDescriptor {
	return file_rv_proto_enumTypes[0].Descriptor()
}

func (FileRequest_Project) Type() protoreflect.EnumType {
	return &file_rv_proto_enumTypes[0]
}

func (x FileRequest_Project) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileRequest_Project.Descriptor instead.
func (FileRequest_Project) EnumDescriptor() ([]byte, []int) {
	return file_rv_proto_rawDescGZIP(), []int{0, 0}
}

type FileResponse_Status int32

const (
	FileResponse_UNKNOWN FileResponse_Status = 0
	FileResponse_SUCCESS FileResponse_Status = 1
	FileResponse_FAIL    FileResponse_Status = 2
)

// Enum value maps for FileResponse_Status.
var (
	FileResponse_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "SUCCESS",
		2: "FAIL",
	}
	FileResponse_Status_value = map[string]int32{
		"UNKNOWN": 0,
		"SUCCESS": 1,
		"FAIL":    2,
	}
)

func (x FileResponse_Status) Enum() *FileResponse_Status {
	p := new(FileResponse_Status)
	*p = x
	return p
}

func (x FileResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_rv_proto_enumTypes[1].Descriptor()
}

func (FileResponse_Status) Type() protoreflect.EnumType {
	return &file_rv_proto_enumTypes[1]
}

func (x FileResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileResponse_Status.Descriptor instead.
func (FileResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_rv_proto_rawDescGZIP(), []int{1, 0}
}

type FileRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The full path of the file from the rsync top directory, ie:
	// path: rsync://archive.routeviews.org/routeviews/bgpdata/2021.03/UPDATES/updates.20210331.2345.bz2
	//   is: routeviews/bgpdata/2021.03/UPDATES/updates.20210331.2345.bz2
	Filename string `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	// A md5sum of the file content.
	Md5Sum string `protobuf:"bytes,2,opt,name=md5sum,proto3" json:"md5sum,omitempty"`
	// The actual file content, as bytes.
	Content []byte `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	// Whether or not to convert the file. Not all files uploaded should be converted.
	ConvertSql bool `protobuf:"varint,4,opt,name=convert_sql,json=convertSql,proto3" json:"convert_sql,omitempty"`
	// project is a list of senders of data to this storage system.
	// Each project may require different processing steps to accomplish the final stoarge goals.
	Project FileRequest_Project `protobuf:"varint,5,opt,name=project,proto3,enum=rv.proto.FileRequest_Project" json:"project,omitempty"`
}

func (x *FileRequest) Reset() {
	*x = FileRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rv_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRequest) ProtoMessage() {}

func (x *FileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rv_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRequest.ProtoReflect.Descriptor instead.
func (*FileRequest) Descriptor() ([]byte, []int) {
	return file_rv_proto_rawDescGZIP(), []int{0}
}

func (x *FileRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *FileRequest) GetMd5Sum() string {
	if x != nil {
		return x.Md5Sum
	}
	return ""
}

func (x *FileRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *FileRequest) GetConvertSql() bool {
	if x != nil {
		return x.ConvertSql
	}
	return false
}

func (x *FileRequest) GetProject() FileRequest_Project {
	if x != nil {
		return x.Project
	}
	return FileRequest_UNKNOWN
}

type FileResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Return a simple status value success/fail.
	Status FileResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=rv.proto.FileResponse_Status" json:"status,omitempty"`
	// If the status is FAIL, provide an error string to be logged.
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

func (x *FileResponse) Reset() {
	*x = FileResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rv_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileResponse) ProtoMessage() {}

func (x *FileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rv_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileResponse.ProtoReflect.Descriptor instead.
func (*FileResponse) Descriptor() ([]byte, []int) {
	return file_rv_proto_rawDescGZIP(), []int{1}
}

func (x *FileResponse) GetStatus() FileResponse_Status {
	if x != nil {
		return x.Status
	}
	return FileResponse_UNKNOWN
}

func (x *FileResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_rv_proto protoreflect.FileDescriptor

var file_rv_proto_rawDesc = []byte{
	0x0a, 0x08, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x72, 0x76, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8e, 0x02, 0x0a, 0x0b, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x6d, 0x64, 0x35, 0x73, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6d, 0x64, 0x35, 0x73, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x5f, 0x73, 0x71,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74,
	0x53, 0x71, 0x6c, 0x12, 0x37, 0x0a, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x6a,
	0x65, 0x63, 0x74, 0x52, 0x07, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x22, 0x57, 0x0a, 0x07,
	0x50, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f,
	0x57, 0x4e, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x4f, 0x55, 0x54, 0x45, 0x56, 0x49, 0x45,
	0x57, 0x53, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x52, 0x4f, 0x55, 0x54, 0x45, 0x56, 0x49, 0x45,
	0x57, 0x53, 0x5f, 0x52, 0x49, 0x42, 0x10, 0x04, 0x12, 0x0c, 0x0a, 0x08, 0x52, 0x49, 0x50, 0x45,
	0x5f, 0x52, 0x49, 0x53, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x52, 0x50, 0x4b, 0x49, 0x5f, 0x52,
	0x41, 0x52, 0x43, 0x10, 0x03, 0x22, 0x98, 0x01, 0x0a, 0x0c, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x23, 0x0a,
	0x0d, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x2c, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b, 0x0a, 0x07, 0x53, 0x55, 0x43,
	0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x46, 0x41, 0x49, 0x4c, 0x10, 0x02,
	0x32, 0x41, 0x0a, 0x02, 0x52, 0x56, 0x12, 0x3b, 0x0a, 0x0a, 0x46, 0x69, 0x6c, 0x65, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x12, 0x15, 0x2e, 0x72, 0x76, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x72, 0x76,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x72, 0x6f, 0x75, 0x74, 0x65, 0x76, 0x69, 0x65, 0x77, 0x73, 0x2f, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2d, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2d, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x72, 0x76, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_rv_proto_rawDescOnce sync.Once
	file_rv_proto_rawDescData = file_rv_proto_rawDesc
)

func file_rv_proto_rawDescGZIP() []byte {
	file_rv_proto_rawDescOnce.Do(func() {
		file_rv_proto_rawDescData = protoimpl.X.CompressGZIP(file_rv_proto_rawDescData)
	})
	return file_rv_proto_rawDescData
}

var file_rv_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_rv_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rv_proto_goTypes = []interface{}{
	(FileRequest_Project)(0), // 0: rv.proto.FileRequest.Project
	(FileResponse_Status)(0), // 1: rv.proto.FileResponse.Status
	(*FileRequest)(nil),      // 2: rv.proto.FileRequest
	(*FileResponse)(nil),     // 3: rv.proto.FileResponse
}
var file_rv_proto_depIdxs = []int32{
	0, // 0: rv.proto.FileRequest.project:type_name -> rv.proto.FileRequest.Project
	1, // 1: rv.proto.FileResponse.status:type_name -> rv.proto.FileResponse.Status
	2, // 2: rv.proto.RV.FileUpload:input_type -> rv.proto.FileRequest
	3, // 3: rv.proto.RV.FileUpload:output_type -> rv.proto.FileResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rv_proto_init() }
func file_rv_proto_init() {
	if File_rv_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rv_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rv_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rv_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rv_proto_goTypes,
		DependencyIndexes: file_rv_proto_depIdxs,
		EnumInfos:         file_rv_proto_enumTypes,
		MessageInfos:      file_rv_proto_msgTypes,
	}.Build()
	File_rv_proto = out.File
	file_rv_proto_rawDesc = nil
	file_rv_proto_goTypes = nil
	file_rv_proto_depIdxs = nil
}
